### ISSUE TITLE
How to run TTT example?

### ISSUE THREAD

**Issue by 5angjun** [LearnLib/learnlib#125]
If you chose a blank issue template to ask a general question about LearnLib, please consider using the [Discussions](https://github.com/LearnLib/learnlib/discussions) page instead.

Hi there.
i'm trying to execute TTT algorithm demo.
from https://github.com/LearnLib/learnlib-ttt

so i couldn't execute this TTT algorithm demo.
Can you show the example?

![image](https://github.com/LearnLib/learnlib/assets/76202024/1e9fd80f-e220-481f-bcdb-8db2c44659b0)

```

git clone https://github.com/LearnLib/learnlib-ttt.git
cd learnlib-ttt/experiments


sudo apt install default-jdk
sudo apt-get install maven
apt-get install gnuplot -y

./run.sh
./plot-results.sh
```
the ./run.sh result : there is no results folder after run ./run.sh
so ./plot-results.sh cannot find results.

**Comment by mtf90** [comment]
Closed in favor of #124
