### ISSUE TITLE
Hidden nondeterminism in ADTLearner

### ISSUE THREAD

**Issue by stateMachinist** [LearnLib/learnlib#137]
I've noticed there is some slight nondeterminism inside the ADTLearner. I found the problem with version 0.17, but it seems to persist in the current nightly. I've built a minimal example against the latest snapshot:

```
import de.learnlib.algorithm.LearningAlgorithm.MealyLearner;
import de.learnlib.algorithm.adt.learner.ADTLearnerBuilder;
import de.learnlib.driver.simulator.MealySimulatorSUL;
import de.learnlib.filter.statistic.oracle.CounterAdaptiveQueryOracle;
import de.learnlib.oracle.EquivalenceOracle.MealyEquivalenceOracle;
import de.learnlib.oracle.equivalence.MealyRandomWpMethodEQOracle;
import de.learnlib.oracle.membership.MealySimulatorOracle;
import de.learnlib.oracle.membership.SULAdaptiveOracle;
import net.automatalib.automaton.transducer.impl.CompactMealy;
import net.automatalib.exception.FormatException;
import net.automatalib.serialization.dot.DOTParsers;
import net.automatalib.util.automaton.Automata;

import java.io.IOException;
import java.util.*;

public class ADTTest {

    public static void main(String[] args) {
        final var model = loadModel("tcp_client_ubuntu.dot");
        for (int eqoSeed = 0; eqoSeed < 100; eqoSeed++) {
            long last = 0;
            for (int i = 0; i < 10; i++) {
                final var mqo = new CounterAdaptiveQueryOracle<>(new SULAdaptiveOracle<>(new MealySimulatorSUL<>(model)));
                final var learner = new ADTLearnerBuilder<String, String>().withAlphabet(model.getInputAlphabet()).withOracle(mqo).create();
                final var eqo = new MealyRandomWpMethodEQOracle<>(new MealySimulatorOracle<>(model), 0, 4, 1000000, new Random(eqoSeed), 1);
                learnToExhaustion(model, learner, eqo);
                final long cnt = mqo.getResetCount();
                if (i == 0) {
                    last = cnt;
                } else if (cnt != last) {
                    throw new RuntimeException("seed: " + eqoSeed + ", cnt 1: " + last + ", cnt 2: " + cnt);
                }
            }
        }
    }

    private static CompactMealy<String, String> loadModel(String name) {
        try {
            final var is = Main.class.getClassLoader().getResourceAsStream(name);
            return DOTParsers.mealy().readModel(is).model;
        } catch (FormatException | IOException e) {
            throw new RuntimeException(e.getMessage());
        }
    }

    private static void learnToExhaustion(CompactMealy<String, String> model,
                                          MealyLearner<String, String> learner,
                                          MealyEquivalenceOracle<String, String> eqo) {
        learner.startLearning();
        while (true) {
            if (Automata.findSeparatingWord(model, learner.getHypothesisModel(), model.getInputAlphabet()) == null) {
                return;
            }

            // the model is still incomplete
            var cex = eqo.findCounterExample(learner.getHypothesisModel(), model.getInputAlphabet());
            if (cex == null) {
                throw new RuntimeException("counterexample exists, but was not found");
            }

            learner.refineHypothesis(cex);
        }
    }
}
```

Running this code, I receive:

```
Exception in thread "main" java.lang.RuntimeException: seed: 25, cnt 1: 431, cnt 2: 422
	at ADTTest.main(ADTTest.java:32)
```

The model is taken from [here](https://gitlab.com/felixwallner/learn-combinations/-/tree/master/input/mealy/principle/BenchmarkTCP). Interestingly, this issue does not occur with every model (or potentially only more rarely with some models than others). Additionally, even if it occurs, the nondeterminism seems to be rare (i.e. in this example, when I do not throw an exception and instead only perform a print and then continue the outer loop, I find that 5 ouf 100 seeds are associated with nondeterminism). However, I can run above code many times and always receive the same output, which seems to suggest that there is some kind of causality involved?

I've noticed this problem while checking the reproducibility of a benchmark I've built. The differences I've observed are all small and do not impact my results in any significant way. But ideally, I would like the benchmark to always produce exactly the same result for any specific combination of test seed, model and learner, so that the results can be verified exactly during artifact evaluation. And indeed, every other learner in my benchmark behaves completely deterministic.

From a quick glance through the _ADTLearner_, I could not identify the source of nondeterminism. The learner itself does not seem to make any use of randomness (at least `grep -lri rand *` inside the _adt_ directory returns no results). It seems to me that there is some kind of hidden program state that impacts the learner and is transferred across loop iterations. This would explain nondeterminism in parallelized experiments.

**Comment by mtf90** [comment]
What a find! The problem is related to the `DefaultExtender`/`DefensiveADS` classes in which entries of `HashMap`s are iterated to compute new ADSs. Their order is based on the objects' hash value which may change across multiple invocations (since new objects are used).

The fix itself is rather simple and small (switching to `LinkedHashMap`s). However, I want to include an integration-test to check other ADS computations as well, which I'll have to think about a little bit.
