### ISSUE TITLE
Bug in profiling counterexamples

### ISSUE THREAD

**Issue by mh12345** [LearnLib/learnlib#27]
The time it takes to search for a counterexample in the last round is not tracked. Therefore the shown time by learnlib is lower than the actual time the searching for counterexamples took to execute.

In the class de.learnlib.experiments.Experiment.java (line 89-95)
you can see that the profileStop statement won't be executed when there is no counterexample found:

profileStart("Searching for counterexample");
DefaultQuery<I, D> ce = equivalenceAlgorithm.findCounterExample(hyp, inputs);
if (ce == null) {
done = true;
continue;
}
profileStop("Searching for counterexample");

Simply placing the profileStop statement right after the findCounterExample statement instead will solve this issue.

**Comment by misberner** [comment]
Thanks for spotting this. Moving the `profileStop` call before the `if` statement should indeed do the trick.
