### ISSUE TITLE
Bug in Wp-method

### ISSUE THREAD

**Issue by Jaxan** [LearnLib/learnlib#29]
As far as I understand the paper of Fujiwara (and other relevant literature), the Wp-method works as follows:

1. We first test states: ```state prefix * middle part * suffix```, where ```suffix``` are drawn from a global set.
2. Secondly we test transitions: ```transition prefix * middle * suffix```, where the ```suffix``` is draw from a set which is relevant for a specific state, namely the state after applying ```transition prefix * middle```. But in the implementation the state being used is the one after applying only ```transition prefix```, as seen here: [line 131](https://github.com/LearnLib/learnlib/blob/develop/eqtests/basic-eqtests/src/main/java/de/learnlib/eqtests/basic/WpMethodEQOracle.java#L131)

**Comment by misberner** [comment]
This is entirely correct, I will change the implementation of the Wp method accordingly.
