### ISSUE TITLE
Make SULOracle extensible

### ISSUE THREAD

**Issue by praseodym** [LearnLib/learnlib#33]
90690154c749ba51aecc58718e9dcd1b4982bc34 changed the `SULOracle` class to use a `private static ` method for `answerQuery`. This breaks any code that extends the class to override the  `answerQuery` method. It would be good to make the `SULOracle` class extensible by not using any `private` or `static` methods.

**Comment by Jaxan** [comment]
It doesn't change the method, it only introduces a new one, which does not make sense to be overridden.

Since it is a new method, you can still override the original `answerQuery` defined in `MembershipOracle`. So it is still extensible.

**Comment by praseodym** [comment]
I wanted to add logging to the `answerQuery` in `SULOracle`. The easiest way to do that would be to extend `SULOracle` and override `answerQuery` . Because that is a static method, I had to make a verbatim copy of `SULOracle` to accomplish what I wanted to do. Not too big of a problem though.

**Comment by Jaxan** [comment]
I think adding logging here does not really make sense. It is much easier to make a `MembershipOracle` which logs every query and then passes them along to some delegate (for example the `SULOracle` without logging). Such a modular design should be easy to implement, right?

Or another way is to wrap the `SUL` in a new one which does the logging.

**Comment by praseodym** [comment]
Makes sense. Let's close this one then :)
