### ISSUE TITLE
Error while importing package

### ISSUE THREAD

**Issue by bazali** [LearnLib/learnlib#44]
Hello!
I am a newcomer. Please, help me.
I have downloaded the source code from the link https://github.com/LearnLib/learnlib via code tab using the option of "clone or download" button and downloaded folder is "learnlib-develop". I import this in Eclipse (with Maven plugin configured) .
It is giving error in Exmaple1
import de.learnlib.algorithms.lstargeneric.mealy.ExtensibleLStarMealyBuilder;

And in Exmaple2
import de.learnlib.algorithms.lstargeneric.mealy.ExtensibleLStarMealyBuilder;
And also in pom file
at ${logback.version}

Please help me ...why it is so....

**Comment by mtf90** [comment]
Hi @bazali,

the builder classes for the learning algorithms are automatically generated during the build lifecycle of maven and should (for the L* builder) reside somewhere under `algorithms/lstar-generic/target/generated-sources/`.

It looks like Eclipse did not correctly execute the lifecycle phases to generate these files. Could you maybe try to explicitly run a "mvn package" on the learnlib-parent project, and check if everything compiles fine (and maybe hit "Refresh" in Eclipse afterwards)?

Also note, that the current development version of learnlib also requires the development version of [automatlib](https://github.com/LearnLib/automatalib).

**Comment by bazali** [comment]
Thanks Brother Issue Solved Now...... The link #32 i.e https://github.com/LearnLib/learnlib/issues/32
helped me alot.....
Now everything is fine....
