### ISSUE TITLE
Potential bug in counterexample handling

### ISSUE THREAD

**Issue by fhowar** [LearnLib/learnlib#6]
In class de.learnlib.counterexamples.LocalSuffixFinders

line 204:

int low = asTransformer.isAccessSequence(prefix) ? prefixLen : prefixLen-1;

Why do you use  prefixLen-1? Shouldn't this rather be 0?

**Comment by aschieweck** [comment]
Well, this is a rather old issue and the line in question seems to be already gone from the source code. So I think it is finally time to close this issue.
