### ISSUE TITLE
Converting DFA to regex?

### ISSUE THREAD

**Issue by breandan** [LearnLib/learnlib#75]
Hello, thanks for maintaining this great library! Can you tell me whether LearnLib currently offers a way to convert DFA to regular expressions (e.g. using the [state elimination method](https://cs.stackexchange.com/a/2389/74308)) or learning regexes directly, similar to [Frak](https://github.com/noprompt/frak)? If not, would you be open to accepting a PR adding support for [regular grammar induction](https://en.wikipedia.org/wiki/Induction_of_regular_languages) or is this functionality out of scope? Thank you!

**Comment by mtf90** [comment]
Dear @breandan, currently we don't support regular expressions as a first-level concept and we don't plan on doing so, but this doesn't mean we're not open to PRs regarding this issue ;). However, if you plan on contributing, I think it would make sense to first discuss what you have in mind, to see if this isn't already achievable by the current infrastructure (see below).

You can use regular expressions in AutomataLib and LearnLib with the help of the [BRICS library](https://www.brics.dk/automaton/), which supports constructing automata from regular expressions and which can be integrated into AutomataLib's/LearnLib's type system via the [brics-adapter module](https://github.com/LearnLib/automatalib/tree/develop/adapters) (see [here](https://github.com/LearnLib/automatalib/blob/develop/examples/src/main/java/net/automatalib/examples/brics/SimpleBricsExample.java) for an example). From the top of my head, I don't know if the reverse is possible as well.

As for learning a regular expression-based system, it should be as easy as to provide a membership oracle implementation that answers queries based on whether they match the regular expression or not (or a set of accepted/rejected words if you prefer a passive learning approach). However, this would yield a DFA-based representation, not an RE-based one.

**Comment by breandan** [comment]
Hi @mtf90, thank you for your detailed reply! I had previously investigated using BRICS, but was unaware of the adapter module you shared above, which seems like a good place to start. However it does not appear to support bidirectional translation. There is a tool called [JFLAP](http://www.jflap.org/) which supports [DFA to RegEx](http://www.jflap.org/modules/ConvertedFiles/DFA%20to%20Regular%20Expression%20Conversion%20Module.pdf) translation and contains an implementation [Arden's Lemma](https://github.com/LakshmiAntin/JFLAPEnhanced/blob/cbb1e6a52f44c826fcb082c85cba9e5f09dcdb33/gui/action/ArdenLemma.java) which may be helpful for reference purposes, although is primarily intended as a teaching aid and unsuitable for practical applications.

One possibility is to generate a RegEx directly from examples as supported by [frak](https://github.com/noprompt/frak), [rgxg](https://github.com/rgxg/rgxg), [Grex](https://github.com/pemistahl/grex), [RegexGenerator](https://github.com/MaLeLabTs/RegexGenerator), et al., which could be converted into an automaton using the brics-adapter as you mentioned. Another possibility is to generate both RegEx and DFA using passive learning, however the languages they recognize are not guaranteed to be the same. From a usability perspective, it would be convenient to have a human-readable representation which is formally equivalent to the automaton.

As someone who is less familiar with the grammar induction literature, can you help me understand the benefits and disadvantages of translating from membership queries to automata directly, instead of building a regular expression, compiling to an automaton, then minimizing? It would seem these two language learning approaches are largely oblivious to each other's work, and unless I am missing something, it seems that RegEx/DFA translation is a fairly straightforward process. Thank you again!

**Comment by mtf90** [comment]
@breandan, are there any questions or issues left as to why this ticket should remain open or can it be closed?

**Comment by breandan** [comment]
I think that about covers it. I’ll open another ticket if I have any other questions, thanks for your detailed reply!

**Comment by mtf90** [comment]
For general questions, you can also have a look at our [mailing lists](https://github.com/LearnLib/learnlib#mailing-lists). We'd like to keep the issue tracker for concrete code-related bugs or features.
